version: '3.8'

services:
  baikal-manager:
    build:
      context: https://github.com/BuggyPasta/Baikal-Manager.git
      dockerfile: Dockerfile
    container_name: baikal-manager
    privileged: true
    ports:
      - "3000:3000"
    volumes:
      - ${HOST_DATA_DIR}:/data
    env_file:
      - .env
    environment:
      - TZ=Europe/London
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 30s
      retries: 3
      start_period: 5s
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    cap_drop:
      - ALL
    cap_add:
      - NET_BIND_SERVICE
      - CHOWN
      - DAC_OVERRIDE
      - FOWNER
    labels:
      - "com.centurylinklabs.watchtower.enable=false"